openapi: 3.1.0
info:
  title: Title
  description: Title
  version: 1.0.0
paths:
  /sos-form/create-update:
    post:
      tags:
        - Form
      summary: Заполнение анкеты SOS
      operationId: createSosForm
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SosFormDTO'
      responses:
        '201':
          description: Анкета успешно создана
        '400':
          description: Ошибка валидации запроса
  /sos-form/deactivate:
    put:
      tags:
        - Form
      summary: Deactivate SOS form
      operationId: deactivateForm
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                  example: "ABC123"
                  description: "Code of the form to deactivate"
                user_id:
                  type: UUID
                  example: "3789ychbfifnbjebw-vdf-v-dfv-df-vdf-"
                  description: "UUID of user"
              required:
                - code
                - user_id
      responses:
        '200':
          description: Successfully deactivated
        '400':
          description: Invalid code
        '404':
          description: Form not found
        '403':
          description: Activation not allowed — less than 24 hours since last activation
  /sos-form/activate:
    post:
      tags:
        - Form
      summary: Schedule activation of SOS form
      operationId: activateForm
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: UUID
                  example: "fwefsf-esf-sef-se-f-esf-sABC123"
                  description: "UUID of user"
                activateAt:
                  type: string
                  format: date-time
                  example: "2025-08-02T14:00:00Z"
                  description: "Datetime when the form should be activated (UTC)"
              required:
                - code
                - activateAt
      responses:
        '200':
          description: Activation scheduled successfully
        '400':
          description: Invalid input
        '404':
          description: Form not found



components:
  schemas:
    SosFormDTO:
      type: object
      properties:
        userId:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        telegramContact:
          type: string
          example: "@username"
        deactivationCode:
          type: string
          example: "ACT123456"
        address:
          type: string
          example: "г. Москва, ул. Пушкина, д. 1"
        dateTime:
          type: string
          format: date-time
          example: "2025-08-02T12:34:56"
        isReady:
          type: boolean
          example: false
        comment:
          type: string
          example: "Комментарий пользователя"
        lastActivation:
          type: string
          format: date-time
          example: "2025-08-02T13:00:00"
          readOnly: true

  
